### PR TITLE
add sin, cos ops

### PR DESCRIPTION
**Pull request by On-JungWoan**
I added the cos and sin operators. Can you please review?

```python
@converter(torch.Tensor.add, torch.Tensor.__add__, torch.Tensor.__iadd__, torch.Tensor.__radd__, channel_ordering_strategy=ChannelOrderingStrategy.MINIMUM_TRANSPOSITIONS_OR_PYTORCH, autocast=True)
def converter_sin(input, *args, **kwargs):
    def func(input, *args, **kwargs):
        return tf.math.sin(input)
    return func

@converter(torch.Tensor.add, torch.Tensor.__add__, torch.Tensor.__iadd__, torch.Tensor.__radd__, channel_ordering_strategy=ChannelOrderingStrategy.MINIMUM_TRANSPOSITIONS_OR_PYTORCH, autocast=True)
def converter_cos(input, *args, **kwargs):
    def func(input, *args, **kwargs):
        return tf.math.cos(input)
    return func
```

### CODE REVIEW

**Comment by AlexanderLutsenko** [comment]
> @converter(torch.Tensor.add, torch.Tensor.__add__, torch.Tensor.__iadd__, torch.Tensor.__radd__, channel_ordering_strategy=ChannelOrderingStrategy.MINIMUM_TRANSPOSITIONS_OR_PYTORCH, autocast=True)

This should be
> @converter(torch.sin, channel_ordering_strategy=ChannelOrderingStrategy.MINIMUM_TRANSPOSITIONS)

**Comment by On-JungWoan** [comment]
image

**Comment by AlexanderLutsenko** [comment]
@On-JungWoan `ChannelOrderingStrategy.MINIMUM_TRANSPOSITIONS` would be a better fit, just for cleanliness. `MINIMUM_TRANSPOSITIONS_OR_PYTORCH` is used for special occasions when there's more than one inputs which might require broadcasting (`add`, `mul`, etc.)

**Comment by On-JungWoan** [comment]
I fixed it!

**Comment by AlexanderLutsenko** [comment]
Done

**Comment by On-JungWoan** [comment]
Thank you for merging it😊

**Pull request merged**
